version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: muhtaseb-backend
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:testkey123456789012345678901234567890
      - DB_CONNECTION=sqlite
    ports:
      - "8000:8000"
    command: sh -c "php artisan optimize:clear && php artisan migrate --force || true && php -S 0.0.0.0:8000 -t public"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: muhtaseb-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: sh -c "npm install --no-fund --no-audit && npm run dev -- --host 0.0.0.0 --port 5173"

networks:
  default:
    name: muhtaseb-net
