<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Monthly Property Report</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .summary-box { background-color: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .highlight { background-color: #e3f2fd; padding: 15px; border-left: 4px solid #2196f3; margin: 20px 0; }
        .positive { color: #27ae60; font-weight: bold; }
        .negative { color: #e74c3c; font-weight: bold; }
        .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>📊 Monthly Property Investment Report</h1>
            <h2>{{ $month }}</h2>
        </div>
        
        <p>Dear {{ $summary['owner']->name }},</p>
        
        <p>Please find attached your comprehensive monthly property investment report for <strong>{{ $month }}</strong>.</p>
        
        <div class="summary-box">
            <h3>📈 Quick Summary</h3>
            <p><strong>Total Portfolio Income:</strong> <span class="positive">${{ number_format($summary['total_income'], 2) }}</span></p>
            <p><strong>Total Portfolio Expenses:</strong> <span class="negative">${{ number_format($summary['total_expenses'], 2) }}</span></p>
            <p><strong>Net Portfolio Income:</strong> <span class="{{ $summary['net_income'] >= 0 ? 'positive' : 'negative' }}">${{ number_format($summary['net_income'], 2) }}</span></p>
            <p><strong>Your Share:</strong> <span class="positive">${{ number_format($summary['owner_share'], 2) }}</span></p>
            <p><strong>Distributions Received:</strong> <span class="positive">${{ number_format($summary['distributions'], 2) }}</span></p>
            <p><strong>Balance Owed:</strong> <span class="{{ $summary['balance_owed'] >= 0 ? 'positive' : 'negative' }}">${{ number_format($summary['balance_owed'], 2) }}</span></p>
        </div>
        
        <div class="highlight">
            <h3>🏢 Portfolio Overview</h3>
            <p><strong>{{ count($summary['properties']) }}</strong> properties | <strong>{{ $summary['occupancy_summary']['total_units'] }}</strong> total units | <strong>{{ $summary['occupancy_summary']['overall_occupancy_rate'] }}%</strong> occupancy rate</p>
        </div>
        
        <p>The attached PDF contains detailed information including:</p>
        <ul>
            <li>📋 Individual property performance breakdowns</li>
            <li>💰 Income and expense categorization</li>
            <li>🔧 Maintenance request summaries</li>
            <li>📊 Occupancy and tenant information</li>
            <li>💳 Distribution details</li>
        </ul>
        
        <p>If you have any questions about this report or need additional information, please don't hesitate to contact us.</p>
        
        <p>Best regards,<br>
        Property Management Team</p>
        
        <div class="footer">
            <p>This is an automated report generated by the Property Management System.</p>
            <p>Please do not reply to this email. For inquiries, contact your property manager directly.</p>
        </div>
    </div>
</body>
</html>
